[theme]

# Primary accent for interactive elements
primaryColor = '#000099'

# Background color for the main content area
backgroundColor = '#E0E0E0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A0A0A0'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
